- name: restart switchd
  service:
    name: switchd
    state: restarted

- name: reload networking
  service:
    name: networking
    state: reloaded

- name: reload ssh
  service:
    name: ssh
    state: reloaded

- name: restart ntp
  service:
    name: ntp
    state: restarted
