global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'ares'
    static_configs:
      - targets: ['ares:9100']
  - job_name: 'castor'
    static_configs:
      - targets: ['castor:9100']
  - job_name: 'jason'
    static_configs:
      - targets: ['jason:9100']
  - job_name: 'proteus'
    static_configs:
      - targets: ['proteus:9100']
  - job_name: 'charon'
    static_configs:
      - targets: ['charon:9100']
