nodes:
  - hostname: &hostname [ abc ] (FQDN)
    manufacturer: [ abc ]
    model: [ model, i.e. Nexus C9348 ]
    type: [ from 'host', 'vm', 'pdu', 'console', 'network' ]
    os: [ lsb_release -v or show version ]
    resources: //optional
      vcpu: [ integer ]
      vram: [ ram in GB ]
      vdisk: [ storage in GB ]
    interfaces: //1 to N (at least one mandatory)
      management:
        vlan: 701
        cable_id: [ if available ]
        ip: [ a.a.a.a ] //just if IP :-)
        netmask: [ b.b.b.b ]
        neighbor:
          hostname: [ neighboring device hostname - use anchors // or 'vSwitch' if a VM]
          port: [ neighbor port or 'vPort' if a VM ]
      console:
        baud: [ i.e. 9600, 115200 ] //just if serial
        cable_id: [ if available ]
        neighbor:
          hostname: [ neighboring device hostname - use anchors if neighbor is a node in the database ]
          port: [ neighbor port ]

    admin_username: &admin_username admin
    access_method: [ from 'ssh' or 'https' ]
    url: [ ssh://*admin_username@*hostname if pdu, console, vm, host, network - can be https://*hostname ]
