- name: Enable resilient hashing
  lineinfile:
    path:   /etc/cumulus/datapath/traffic.conf
    regexp: '.*resilient_hash_enable .*$'
    line: 'resilient_hash_enable = TRUE'
  register: hashing

- name: Restart switchd
  service:
    name: switchd
    state: restarted
  when: hashing.changed
