---
- name: Add Telegraf repo key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add Telegraf apt repo
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian jessie stable"
    state: present

- name: Add telegraf to list of vrf services
  lineinfile:
    path: /etc/vrf/systemd.conf
    line: telegraf
    state: present

- name: Remove and purge Telegraf
  apt:
    name: telegraf
    state: absent
    purge: yes

- name: Install Telegraf
  apt:
    name: telegraf
    update_cache: yes
    state: present


- name: Copy telegraf configuration
  template:
    src: templates/cumulus/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf

- name: Remove Telegraf in default vrf
  systemd:
    name: telegraf
    state: stopped
    enabled: no

- name: Enable Telegraf in mgmt vrf
  systemd:
    name: telegraf@mgmt
    state: stopped
    enabled: yes

- name: Remove User=telegraf in service config to enable running as root
  lineinfile:
    path: /lib/systemd/system/telegraf.service
    line: User=telegraf
    state: absent

- name: Restart and enable Telegraf in mgmt vrf
  systemd:
    name: telegraf@mgmt
    state: started
    daemon_reload: yes
