- name: Download the ingress-nginx setup templates
  get-url:
    url: {{item}}
    dest: /tmp/ingress-nginx/
    mode: 0700
    with_items:
      - https://raw.githubusercontent.com/TommyKTheDJ/hydra/master/files/ingress-nginx/values.yaml

- name: Install nginx ingress controller using custom values files
  helm:
    host: localhost
    chart:
      name: nginx-ingress
      version: 0.11.1
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
    state: installed
    name: ingress-controller
    namespace: ingress-nginx
    values: /tmp/ingress-nginx/values.yaml
