- name: Install pyhelm
  pip:
    name: pyhelm
    state: latest

- name: Install nginx ingress controller using custom values files
  helm:
    host: localhost
    chart:
      name: nginx-ingress
      version: 0.11.1
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
    state: present
    name: ingress-controller
    namespace: ingress-nginx
    values: "{{item}}"
  with_items:
    - controller.replicaCount=2
    - controller.service.externalTrafficPolicy=Local
    - controller.service.type=nodePort
    - defaultBackend.replicaCount=2
    - rbac.create=true
    - rbac.serviceAccountName=nginx-ingress-serviceaccount
