- name: Install git & pip if not already installed
  apt:
    name: {{item}}
    update_cache: yes
  with_items:
   - git
   - python-pip

- name: Install Jinja2
  pip:
    name: jinja2

- name: Clone the kubespray repo
  git:
    repo: 'https://github.com/kubernetes-incubator/kubespray.git'
    dest: /tmp/kubespray

- name: Edit the k8s-cluster.yml file to enable netchecker
  lineinfile:
    path: /tmp/kubespray/inventory/sample/group_vars/k8s-cluster.yml
    regexp: '^deploy_netchecker'
    line: 'deploy_netchecker: true'

- name: Edit the k8s-cluster.yml file to ensure calico is the networking (doesn't matter, but for consistency)
  lineinfile:
    path: /tmp/kubespray/inventory/sample/group_vars/k8s-cluster.yml
    regexp: '^kube_network_plugin'
    line: 'kube_network_plugin: calico'
