---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: onie-nginx-volume-claim
 namespace: onie
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
