apiVersion: v1
kind: PersistentVolume
metadata:
  name: gv000-onie
  labels:
    storage-tier: gold
    aws-availability-zone: us-east-1
spec:
  capacity:
    storage: 300Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
    readOnly: false
