---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      storage-tier: gold
      aws-availability-zone: us-east-1
