apiVersion: v1
kind: Service
metadata:
  name: onie-nginx-service
  namespace: onie
spec:
  ports:
     -  port: 80
        protocol: TCP
        nodePort: 31653
  selector:
    app: onie-nginx
  type: NodePort
