- name: Create glusterfs daemonset
  shell: kubectl create -f {{ playbook_dir }}/roles/heketi/files/glusterfs-daemonset.yml
- name: Create serviceaccount
  shell: kubectl create -f {{ playbook_dir }}/roles/heketi/files/heketi-service-account.yml
- name: Create clusterrolebinding
  shell: kubectl create clusterrolebinding heketi-gluster-admin --clusterrole=edit \
        --serviceaccount=kube-system:heketi-service-account
- name: Create secret
  shell: kubectl create secret generic heketi-config-secret --from-file={{ playbook_dir }}/roles/heketi/files/heketi.json
- name: Create bootstrap
  shell: kubectl create -f {{ playbook_dir }}/roles/heketi/files/heketi-bootstrap.json
- name: Create topology file
  template:
    src: "{{ playbook_dir }}/roles/heketi/templates/topology.json.j2"
    dest: "{{ playbook_dir }}/roles/heketi/files/gluster_topology.json"
- name: Get pods
  shell: kubectl get pods
  register: pods
