dns_root_domain: hydra.lab
cluster_fqdn: cluster.hydra.lab
dns_servers:
  internal:
    - 10.60.3.29
    - 10.60.3.30
#===================================================
# NTP
#===================================================
ntp_servers:
  internal:
    - 10.60.3.29
    - 10.60.3.30
  external:
    - 216.239.35.4
    - 216.239.35.8
    - 85.254.216.1
    - 37.120.191.245

ntp_timezone: UTC
#===================================================
# DHCP
#===================================================
dhcp_failover_master: hydra-dns-1
dhcp_failover_backup: hydra-dns-2
#===================================================
# KUBERNETES SERVICES
#===================================================
services:
  ingress:
    host: vip.hydra.lab
    namespace: ingress-nginx
    exposed: False
  prometheus:
    host: prometheus.hydra.lab
    namespace: monitoring
    exposed: True
    ports:
      http:
        endpoint_alias: hydra-influxdb
        alias: influxdb-http
        protocol: TCP
        number: 8086
        exposed: True
  fluentd:
    host: fluentd.hydra.lab
    namespace: monitoring
    exposed: True
  elasticsearch:
    namespace: monitoring
    host: elasticsearch.hydra.lab
    exposed: True
    ports:
      http:
        endpoint_alias: elasticsearch
        alias: elastic-http
        protocol: TCP
        number: 9200
        exposed: True
  kibana:
    namespace: monitoring
    host: kibana.hydra.lab
    exposed: True
    ports:
      http:
        endpoint_alias: kibana-http
        alias: kibana-http
        protocol: TCP
        number: 5601
        exposed: True
  grafana:
    host: grafana.hydra.lab
    namespace: monitoring
    exposed: True
    ports:
      http:
        endpoint_alias: dashboard-grafana
        alias: grafana-http
        protocol: TCP
        number: 9999
        exposed: True
#===================================================
# FLUENTD PARAMETERS
#===================================================
fluentd_cpu_limit: 2
fluentd_mem_limit: 1600Mi
fluentd_cpu_requests: 1
fluentd_mem_requests: 800Mi
fluentd_image: "dustnic82/fluentd-elasticsearch-beats:latest"
fluentd_config: fluent.conf
# Path used to store Docker data
fluentd_docker_daemon_graph: "/var/lib/docker"
fluentd_rbac_enabled: true
