snmp_trap_collector: 10.60.50.4
syslog_server: 10.60.50.5
    
dns_root_domain: hydra.lab

dns_servers:
  internal:
    - 10.60.3.29
    - 10.60.3.30


ntp_servers:
  internal:
    - 10.60.3.29
    - 10.60.3.30
  external:
    - 216.239.35.4
    - 216.239.35.8
    - 85.254.216.1
    - 212.59.0.1
    - 37.120.191.245

ntp_timezone: Europe/London

dhcp_failover_master: hydra-dns-1
dhcp_failover_backup: hydra-dns-2


influxdb:
  host: cluster.hydra.lab
  http_port: 8086
  bind_port: 8088
  retention: autogen
  username: cumulus
  password: cumulus
  database: network
  namespace: telemetry

redis:
  namespace: telemetry
