---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka-zookeeper
  labels:
    app: kafka
spec:
  ports:
  - port: 9093
    name: server
  clusterIP: None
  selector:
    app: kafka
