- name: Create temporary device configuration file
  template:
    src: nexus.j2
    dest: "{{ output_folder }}/{{ inventory_hostname }}.conf"

- name: Configure mgmt_switches
  nxos_config:
    transport: cli
    host: "{{ inventory_hostname }}"
    username: "{{ net_username }}"
    password: "{{ net_password }}"
    src: "{{ output_folder }}/{{ inventory_hostname }}.conf"
    save_when: modified

# - name: Delete temporary files
#   file:
#     path: "{{ output_folder }}/{{ inventory_hostname }}.conf"
#     state: absent
