- name: restart switchd
  service:
    name: switchd
    state: restarted

- name: reload networking
  service:
    name: networking
    state: reloaded

- name: restart sshd
  service:
    name: sshd
    state: reloaded

- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: restart dhcpd
  service:
    name: isc-dhcp-server
    state: restarted

- name: restart rsyslogd
  service:
    name: rsyslog
    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted
