---
- name: Create admin users
  uri:
    headers:
      aos_user_id: "{{ aos_token_id }}"
      accept: application/json
      AUTHTOKEN: "{{ aos_token }}"
    url: https://{{ aos_server_hostname }}/api/aaa/users/
    method: POST
    body: "{{ lookup('template','templates/aos/aaa_admins.j2') }}"
    # force_basic_auth: yes
    status_code: 201, 409
    body_format: json
    validate_certs: no
  with_items:
    - "{{ users.admins }}"

- name: Create users
  uri:
    headers:
      aos_user_id: "{{ aos_token_id }}"
      accept: application/json
      AUTHTOKEN: "{{ aos_token }}"
    url: https://{{ aos_server_hostname }}/api/aaa/users/
    method: POST
    body: "{{ lookup('template','templates/aos/aaa_users.j2') }}"
    # force_basic_auth: yes
    status_code: 201, 409
    body_format: json
    validate_certs: no
  with_items:
    - "{{ users.users }}"
