apiVersion: v1
kind: PersistentVolume
metadata:
  name: onie-nginx-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  rbd:
    monitors:
      - 10.60.3.25:6789
      - 10.60.3.27:6789
    pool: hydra-ceph-pool
    image: onie-nginx
    user: admin
    secretRef:
      name: ceph-secret-admin
    fsType: ext4
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onie-nginx-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
