---
- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - isc-dhcp-server
    - rsyslog

- name: Add line to rsyslog config
  template:
    src: "{{ playbook_dir }}/templates/dhcpd/52-hydra-dhcpd.conf.j2"
    dest: /etc/rsyslog.d/52-hydra-dhcpd.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - dhcpd
    - syslog

- name: Create isc-dhcp-server configuration file
  template:
    src: "{{ playbook_dir }}/templates/dhcpd/isc-dhcp-server.j2"
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: 0644
  tags:
    - dhcpd

- name: Configure DHCP static entries
  template:
    src: "{{ playbook_dir }}/templates/dhcpd/dhcpd-hydra-static.conf.j2"
    dest: "/etc/dhcp/dhcpd-hydra-static.conf"
    owner: root
    group: root
    mode: 0644
    force: yes
  tags:
    - dhcpd_static
    - dhcpd

- name: Configure DHCP server
  template:
    src: "{{ playbook_dir }}/templates/dhcpd/dhcpd.conf.j2"
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - dhcpd
    - dhcpd_general

- name: Restart rsyslogd
  service:
    name: rsyslog
    state: restarted

- name: Restart dhcpd
  service:
    name: isc-dhcp-server
    state: restarted
