---
- name: NTP | Stop timedatectl
  command: timedatectl set-ntp no
  ignore_errors: True

- name: NTP | Ensure NTP-related packages are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - ntpdate

- name: NTP | Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: NTP | Generate ntp.conf file
  template:
    src: "{{ playbook_dir }}/templates/common/ntp.conf.j2"
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644

- name: NTP | SNAT on port UDP 123
  iptables:
    table: nat
    chain: PREROUTING
    protocol: udp
    match: udp
    source_port: 123
    jump: SNAT
    to_source: 12512
    state: present
    comment: Alter source port for NTP traffic (blocked by firewall)
  when: inventory_hostname in groups['ntpd']


- name: NTP | tart daemon
  systemd:
    name: ntp
    enabled: yes
    state: restarted
