- name: Configure hostname
  hostname:
    name: "{{ inventory_hostname.split('.')|first }}"

- name: Fix /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '127\.0\.1\.1\s+.*'
    line: "127.0.1.1{{ '\t' + inventory_hostname.split('.')|first }}"
    owner: root
    group: root
    mode: 0644
