---
- name: Configure users
  include_tasks: users.yml
  tags:
    - users

- name: Distribute keys
  include_tasks: keys.yml
  tags:
    - keys

- name: Configure NTP
  include_tasks: ntp.yml
  tags:
    - ntp

- name: Configure Interfaces
  include_tasks: interfaces.yml
  tags:
    - interfaces
    - dns

- name: Configure hostname
  include_tasks: hostname.yml
  tags:
    - hostname

- name: Install using rancher script
  include_tasks: docker.yml
  tags:
    - docker
