- name: Enable resilient hashing
  lineinfile:
    path:   /etc/cumulus/datapath/traffic.conf
    regexp: '.*resilient_hash_enable .*$'
    line: 'resilient_hash_enable = TRUE'
  notify: restart switchd
