---
- name: Ensure NTP-related packages are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - ntpdate

- name: Stop NTP
  systemd:
    name: ntp
    state: stopped

- name: Kill hung processes
  command: pkill ntpd
  ignore_errors: true

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Generate ntp.conf file
  template:
    src: "{{ playbook_dir }}/templates/common/ntp.conf.j2"
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644

- name: Force first sync
  command: ntpd -gq

- name: Start NTP
  systemd:
    name: ntp
    enabled: yes
    state: started
