---
- name: Add Telegraf repo key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add Telegraf apt repo
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian jessie stable"
    state: present

- name: Install Telegraf
  apt:
    name: telegraf
    update_cache: yes
    state: present

- name: Copy telegraf configuration
  template:
    src: templates/worker/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf

- name: Enable and start telegraf
  systemd:
    name: telegraf
    state: started
    enabled: yes
