---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-poddistruptionbudgedt
  namespace: kafka-zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  maxUnavailable: 1
