- name: Modify /etc/network/interfaces for interfaces.d
  lineinfile:
    line: source /etc/network/interfaces.d/*.intf
    path: /etc/network/interfaces
    state: present
  tags:
    - management

- name: Modify /etc/network/interfaces for interfaces.d
  lineinfile:
    regexp: .* [BLOCK|eth0|The primary network interface|vrf mgmt]
    path: /etc/network/interfaces
    state: absent
  tags:
    - management
    - enable_interfaces

- name: Configure mgmt interface
  copy:
    dest: /etc/network/interfaces.d/mgmt.intf
    src: mgmt.conf
  tags:
    - management

- name: Configure vrf mgmt on eth0 interface
  copy:
    dest: /etc/network/interfaces.d/eth0.intf
    src: eth0.conf
  tags:
    - management

- name: Reload networking
  service:
    name: networking
    state: reloaded
  tags:
    - management

- name: Copy License file
  lineinfile:
    path: /tmp/license
    line: "{{ cumulus_license }}"
    create: yes

- name: Install License
  shell: "cl-license -i /tmp/license"
  notify: restart switchd

- name: Stop AoS service
  service:
    name: aos
    state: stopped

- name: Remove AoS folder
  file:
    path: /etc/aos
    state: absent
  tags:
    - aos_agent

- name: Get installation script
  get_url:
    url: https://{{ aos_server_hostname }}/device_agent_images/aos_device_agent.run
    dest: /tmp/aos_device_agent.run
    validate_certs: no
    mode: 0740
  tags:
    - aos_agent

- name: Execute installation script
  shell: /tmp/aos_device_agent.run
  tags:
    - aos_agent

- name: Correct host in aos.conf
  lineinfile:
    path:   /etc/aos/aos.conf
    regexp: '^(metadb = tbt:\/\/)(aos-server)(:29731)$'
    line: '\1{{ aos_server_hostname}}\3'
    backrefs: yes

- name: Restart AoS service
  service:
    name: aos
    state: restarted
