- name: Download docker script
  get_url:
    url: "{{ docker_install_script }}"
    dest: /tmp/docker_install.sh
    mode: 0755

- name: Install docker using rancher shell script
  shell: /tmp/docker_install.sh
