- hosts: baremetals
  gather_facts: no
  become: true
  pre_tasks:
    - name: Import initial user/pwd for first configuration
      include_vars: "{{ playbook_dir }}/files/baremetals/initial.yml"
      tags:
        - initial
  tasks:
    - include_tasks: "{{ playbook_dir }}/tasks/workers/users.yml"
      tags:
        - users

    - include_tasks: "{{ playbook_dir }}/tasks/common/keys.yml"
      tags:
        - keys

    - include_tasks: "{{ playbook_dir }}/tasks/switches/set-locale.yml"
      tags:
        - locale

    - include_tasks: "{{ playbook_dir }}/tasks/common/ntp.yml"
      tags:
        - ntp

    - include_tasks: "{{ playbook_dir }}/tasks/common/filebeat.yml"
      tags:
        - filebeat

    - include_tasks: "{{ playbook_dir }}/tasks/baremetals/install-aos-agent.yml"
      tags:
        - aos
