- hosts: dhcpd_servers
  user: hydra
  become: true
  roles:
    - dhcpd
  tags: dhcpd

- hosts: virtual_workers
  user: hydra
  become: true
  roles:
    - unix_accounts
    - ntpd
  tags:
    - accounts
    - ntpd
