- hosts: switches
  gather_facts: yes
  become: true
  pre_tasks:
    - name: Import initial user/pwd for first configuration
      include_vars: "{{ playbook_dir }}/files/switches/initial.yml"
      tags:
        - initial
  tasks:

    - include_tasks: "{{ playbook_dir }}/tasks/switches/users.yml"
      tags:
        - users

    - include_tasks: "{{ playbook_dir }}/tasks/switches/configure-mgmt-interface.yml"
      tags:
        - mgmt

    - include_tasks: "{{ playbook_dir }}/tasks/switches/set-locale.yml"
      tags:
        - locale

    - include_tasks: "{{ playbook_dir }}/tasks/switches/pre-apt.yml"
      tags:
        - pre-apt

    - include_tasks: "{{ playbook_dir }}/tasks/switches/install-license.yml"
      tags:
        - license

    - include_tasks: "{{ playbook_dir }}/tasks/common/install-aos-agent.yml"
      tags:
        - aos

    - include_tasks: "{{ playbook_dir }}/tasks/switches/resilient-hashing.yml"
      tags:
        - hashing

    - include_tasks: "{{ playbook_dir }}/tasks/switches/ssh-config.yml"
      tags:
        - ssh

    - include_tasks: "{{ playbook_dir }}/tasks/switches/ntp.yml"
      tags:
        - ntp

    - include_tasks: "{{ playbook_dir }}/tasks/switches/keys.yml"
      tags:
        - keys

    - include_tasks: "{{ playbook_dir }}/tasks/switches/telegraf.yml"
      tags:
        - telegraf

    - include_tasks: "{{ playbook_dir }}/tasks/switches/syslog.yml"
      tags:
        - syslog
