- hosts: cumulus
  gather_facts: yes
  become: true
  pre_tasks:
    - name: Import initial user/pwd for first configuration
      include_vars: "{{ playbook_dir }}/files/cumulus/initial.yml"
      when: initial is defined

  tasks:

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/users.yml"
      tags:
        - users

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/configure-mgmt-interface.yml"
      tags:
        - mgmt

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/set-locale.yml"
      tags:
        - locale

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/pre-apt.yml"
      tags:
        - pre-apt

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/install-license.yml"
      tags:
        - license

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/install-aos-agent.yml"
      tags:
        - aos

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/resilient-hashing.yml"
      tags:
        - hashing

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/ssh-config.yml"
      tags:
        - ssh

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/ntp.yml"
      tags:
        - ntp

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/keys.yml"
      tags:
        - keys

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/telegraf.yml"
      tags:
        - telegraf

    - include_tasks: "{{ playbook_dir }}/tasks/common/filebeat.yml"
      tags:
        - filebeat

    - include_tasks: "{{ playbook_dir }}/tasks/cumulus/syslog.yml"
      tags:
        - syslog
