- hosts: dummy
  become: true
  connection: local
  tasks:
    - name: Install PIP dependencies
      pip:
          name: "{{ item }}"
          state: present
      with_items:
          - pandas
          - xlrd
          - netaddr
          - boltons

    - name: Generate Lab Database
      hydra_database:
        src: "{{ playbook_dir }}/shared/hydra_lab_inventory.xlsx"
        hosts_database_dest: "{{ playbook_dir }}/group_vars/all/database.yml"
        subnets_database_dest: "{{ playbook_dir }}/group_vars/all/subnets.yml"
        force: True
