- hosts: dummy
  become: true
  connection: local
  tasks:
    - name: Install PIP dependencies
      pip:
          name: "{{ item }}"
          state: present
      with_items: "{{ pip_packages }}"

    - name: Generate Lab Database
      hydra_database:
        src: "{{ playbook_dir }}/shared/hydra_lab_inventory.xlsx"
        hosts_database_dest: "{{ playbook_dir }}/group_vars/all/database.yml"
        vlans_database_dest: "{{ playbook_dir }}/group_vars/all/vlans.yml"
        force: True
