---
- hosts: cumulus&virtual-machines
  become: true
  gather_facts: no
  tasks:
  - name: Deploy local ssh public key to hosts
    authorized_key:
      user: nicola.arnoldi
      state: present
      manage_dir: yes
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub')}}"
