---
- hosts: consoles
  connection: local
  tasks:
    - include_tasks: tasks/console/main.yml

- hosts: pdus
  connection: local
  tasks:
    - include_tasks: tasks/pdu/main.yml

- hosts: mgmt_switches
  connection: local
  tasks:
    - include_tasks: tasks/mgmt_switch/main.yml
