- hosts: localhost
  connection: local
  roles:
    - {role: ssh_keys, tags: keygen}

- hosts: cumulus
  strategy: free
  become: true
  roles:
    - {role: ssh_keys, tags: switches}

- hosts: virtual-machines
  strategy: free
  become: true
  tags: vms
  roles:
    - {role: ssh_keys, tags: vms}

- hosts: mgmt-switches
  strategy: free
  tags: switches
  gather_facts: false
  connection: local
  roles:
    - {role: ssh_keys, tags: switches, ansible_os: nx_os}
