- hosts: virtual-machines
  gather_facts: no
  become: true
  pre_tasks:
    - name: Import initial user/pwd for first configuration
      include_vars: "{{ playbook_dir }}/files/workers/initial.yml"
      when: initial is defined
      tags:
        - always

  tasks:
    - name: Configure Interfaces
      include_tasks: "{{ playbook_dir }}/tasks/workers/interfaces.yml"
      tags:
        - interfaces
        - dns

    - name: Install dependencies
      include_tasks: "{{ playbook_dir }}/tasks/workers/apt.yml"
      tags:
        - apt

    - name: Configure users
      include_tasks: "{{ playbook_dir }}/tasks/workers/users.yml"
      tags:
        - users

    - name: Distribute keys
      include_tasks: "{{ playbook_dir }}/tasks/common/keys.yml"
      tags:
        - keys
    
    - name: Configure hostname
      include_tasks: "{{ playbook_dir }}/tasks/common/hostname.yml"
      tags:
        - hostname

    - name: Install docker
      include_tasks: "{{ playbook_dir }}/tasks/workers/docker.yml"
      tags:
        - docker

    - name: Turn off swap
      include_tasks: "{{ playbook_dir }}/tasks/workers/swapoff.yml"
      when: inventory_hostname in groups['kube-nodes']
      tags:
        - docker
        - swap

    - name: Remove floppy mod
      command: rmmod floppy
      ignore_errors: True

    - name: Install and configure filebeat
      include_tasks: "{{ playbook_dir }}/tasks/common/filebeat.yml"
      tags:
        - filebeat
        - monitoring

    - name: Install and configure NTP
      include_tasks: "{{ playbook_dir }}/tasks/common/ntp.yml"
      tags:
        - ntp
