- hosts: virtual-machines
  gather_facts: yes
  pre_tasks:
    - name: Import initial user/pwd for first configuration
      include_vars: includes/initial-virtual-machines.yml
      when: initial is defined
  become: true
  tasks:
    - name: Install dependencies
      include_tasks: apt.yml
      tags:
        - apt

    - name: Configure users
      include_tasks: users.yml
      tags:
        - users

    - name: Distribute keys
      include_tasks: keys.yml
      tags:
        - keys

    - name: Configure NTP
      include_tasks: ntp.yml
      tags:
        - ntp

    - name: Configure Interfaces
      include_tasks: interfaces.yml
      tags:
        - interfaces
        - dns

    - name: Configure hostname
      include_tasks: hostname.yml
      tags:
        - hostname

    - name: Install using rancher script
      include_tasks: docker.yml
      tags:
        - docker

    - name: Turn off swap
      include_tasks: swapoff.yml
      when: inventory_hostname in groups['kubernetes']
      tags:
        - docker
