- hosts: virtual-machines
  gather_facts: no
  pre_tasks:
    - name: Import initial user/pwd for first configuration
      include_vars: includes/initial-virtual-machines.yml
      when: initial is defined
  become: true
  tasks:
    - name: Install dependencies
      include_tasks: "{{ playbook_dir }}/tasks/worker/apt.yml"
      tags:
        - apt

    - name: Configure users
      include_tasks: "{{ playbook_dir }}/tasks/worker/users.yml"
      tags:
        - users

    - name: Distribute keys
      include_tasks: "{{ playbook_dir }}/tasks/worker/keys.yml"
      tags:
        - keys

    - name: Configure Interfaces
      include_tasks: "{{ playbook_dir }}/tasks/worker/interfaces.yml"
      tags:
        - interfaces
        - dns

    - name: Configure hostname
      include_tasks: "{{ playbook_dir }}/tasks/worker/hostname.yml"
      tags:
        - hostname

    - name: Install using rancher script
      include_tasks: "{{ playbook_dir }}/tasks/worker/docker.yml"
      tags:
        - docker

    - name: Turn off swap
      include_tasks: "{{ playbook_dir }}/tasks/worker/swapoff.yml"
      when: inventory_hostname in groups['kubernetes']
      tags:
        - docker
        - swap

- hosts: virtual-machines:!ntpd
  gather_facts: yes
  become: true
  tasks:
    - name: Configure NTP
      import_tasks: "{{ playbook_dir }}/tasks/common/ntp.yml"
      tags:
        - ntp
