- name: Stop AoS service
  service:
    name: aos
    state: stopped
  ignore_errors: true

- name: Remove AoS folder
  file:
    path: /etc/aos
    state: absent
  tags:
    - aos_agent

- name: Copy inventory to AOS server
  template:
    src: "{{ playbook_dir }}/templates/common/aos_inventory.j2"
    dest: /tmp/inventory

- name: Get installation script
  get_url:
    url: https://{{ aos.server_fqdn }}/device_agent_images/aos_device_agent.run
    dest: /tmp/aos_device_agent.run
    validate_certs: no
    force: yes
    mode: 0740
  tags:
    - aos_agent

- name: Execute installation script
  shell: /tmp/aos_device_agent.run
  tags:
    - aos_agent

- name: Correct host in aos.conf
  template:
    dest: /etc/aos/aos.conf
    src: "{{ playbook_dir }}/templates/common/aos.conf.j2"

- name: Restart AoS service
  service:
    name: aos
    state: restarted
