- name: Tune SSH for faster connections
  lineinfile:
    path:   /etc/ssh/sshd_config
    regexp: 'UsePAM *'
    line: 'UsePAM yes'

- name: Tune SSH for faster connections
  lineinfile:
    path:   /etc/ssh/sshd_config
    regexp: 'UseDNS *'
    line: 'UseDNS no'

- name: Restart sshd
  service:
    name: sshd
    state: restarted
