- name: Add Gluster APT repository
  apt_repository:
    update_cache: yes
    repo: 'ppa:gluster/glusterfs-3.12'
  tags:
    - apt

- name: Install xfs glusterfs and dependencies
  apt:  name={{item}}
  with_items:
    - glusterfs-client
    - ntp
    - python
  tags:
    - apt
