- name: Add Gluster APT repository
  apt_repository:
    update_cache: yes
    repo: 'ppa:gluster/glusterfs-4.0'

- name: Install xfs glusterfs and dependencies
  apt:  name={{item}}
  with_items:
    - glusterfs*
    - xfsprogs
    - ntp
    - ntpdate
