- name: Configure interfaces
  template:
    src: "{{ playbook_dir }}/templates/workers/interfaces.j2"
    dest: /etc/network/interfaces
    backup: yes

- name: Restart networking
  service:
    name: network
    state: restarted
