- name: Configure interfaces
  template:
    src: "{{ playbook_dir }}/templates/workers/interfaces.j2"
    dest: /etc/network/interfaces
    backup: yes
  tags:
    - interfaces

- name: Restart networking
  service:
    name: networking
    state: restarted
  tags:
    - interfaces
